"""create financial_data table

Revision ID: 2698f8968080
Revises: 
Create Date: 2023-04-14 01:40:51.630631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2698f8968080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=32), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('open_price', sa.DECIMAL(precision=19, scale=2), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=19, scale=2), nullable=False),
    sa.Column('volume', mysql.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='_symbol_date_unique'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_index(op.f('ix_financial_data_date'), 'financial_data', ['date'], unique=False)
    op.create_index(op.f('ix_financial_data_symbol'), 'financial_data', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_data_symbol'), table_name='financial_data')
    op.drop_index(op.f('ix_financial_data_date'), table_name='financial_data')
    op.drop_table('financial_data')
    # ### end Alembic commands ###
